(() => {
  "use strict";
  const config = window.SITE_CONFIG;
  const $ = (id) => document.getElementById(id);
  const audio = $("audio-player");
  if (!audio || !config?.music) return;
  const songs = config.music.songs;
  const title = $("song-name"); const artist = $("song-artist"); const progress = $("progress"); const current = $("current-time"); const duration = $("duration"); const card = document.querySelector(".music-card"); const playButton = $("play-button");
  let index = 0; let sources = []; let sourceIndex = 0; let shouldPlay = false; let scrubbing = false;
  const time = (seconds) => { if (!Number.isFinite(seconds) || seconds < 0) return "0:00"; const value = Math.floor(seconds); const hours = Math.floor(value / 3600); const minutes = Math.floor((value % 3600) / 60); const secondsText = String(value % 60).padStart(2, "0"); return hours ? `${hours}:${String(minutes).padStart(2, "0")}:${secondsText}` : `${minutes}:${secondsText}`; };
  const parse = (file) => { const base = file.replace(/\.(flac|mp3|wav|ogg|m4a|aac|opus)$/i, ""); const split = base.indexOf(" - "); return split < 0 ? { title: base, artist: "" } : { artist: base.slice(0, split), title: base.slice(split + 3) }; };
  const encodedSources = (file) => [...new Set([file, file.normalize("NFC"), file.normalize("NFD")])].map((value) => value.split("/").map(encodeURIComponent).join("/"));
  const available = () => Number.isFinite(audio.duration) && audio.duration > 0;
  const paint = (value) => progress?.style.setProperty("--fill", `${Math.max(0, Math.min(100, value))}%`);
  const state = () => { const playing = !audio.paused; playButton?.classList.toggle("playing", playing); playButton?.setAttribute("aria-label", playing ? "Pause" : "Play"); card?.classList.toggle("is-playing", playing); };
  const failed = () => { card?.classList.add("has-error"); if (title) title.textContent = "Hiện không có bài nào đang phát"; if (artist) artist.textContent = "Không thể tải tệp âm thanh"; progress && (progress.disabled = true); };
  const render = () => { const track = parse(songs[index]); if (title) { title.textContent = track.title; title.title = track.title; } if (artist) artist.textContent = track.artist; card?.classList.remove("has-error"); };
  const play = () => { shouldPlay = true; const promise = audio.play(); promise?.catch((error) => { if (error.name !== "AbortError") state(); }); };
  const load = (next, autoplay = false) => { if (!songs.length) return failed(); index = (next + songs.length) % songs.length; sources = encodedSources(songs[index]); sourceIndex = 0; shouldPlay = autoplay; audio.src = sources[0]; audio.load(); render(); if (autoplay) play(); };
  const next = () => load(index + 1, true); const previous = () => audio.currentTime > 3 ? (audio.currentTime = 0) : load(index - 1, true);
  playButton?.addEventListener("click", () => audio.paused ? play() : (shouldPlay = false, audio.pause())); $("prev-button")?.addEventListener("click", previous); $("next-button")?.addEventListener("click", next);
  progress?.addEventListener("pointerdown", () => { if (!progress.disabled) scrubbing = true; }); progress?.addEventListener("input", () => { if (!available()) return; const value = Number(progress.value); paint(value); if (current) current.textContent = time(audio.duration * value / 100); }); progress?.addEventListener("change", () => { if (available()) audio.currentTime = audio.duration * Number(progress.value) / 100; scrubbing = false; }); progress?.addEventListener("pointerup", () => { scrubbing = false; });
  audio.addEventListener("play", state); audio.addEventListener("pause", state); audio.addEventListener("ended", next); audio.addEventListener("error", () => { if (sourceIndex + 1 < sources.length) { sourceIndex += 1; audio.src = sources[sourceIndex]; audio.load(); if (shouldPlay) play(); } else failed(); });
  audio.addEventListener("loadedmetadata", () => { if (duration) duration.textContent = time(audio.duration); if (progress) progress.disabled = !available(); }); audio.addEventListener("timeupdate", () => { if (!available()) return; if (!scrubbing) { const value = audio.currentTime / audio.duration * 100; if (progress) progress.value = value; paint(value); if (current) current.textContent = time(audio.currentTime); } });
  const formatter = new Intl.DateTimeFormat("en-GB", { timeZone: config.music.timezone, hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false, hourCycle: "h23" }); const renderClock = () => { const clock = $("clock"); if (clock) clock.textContent = formatter.format(new Date()); }; renderClock(); window.setInterval(renderClock, 1000);
  if ("mediaSession" in navigator) Object.entries({ play, pause: () => { shouldPlay = false; audio.pause(); }, previoustrack: previous, nexttrack: next }).forEach(([action, handler]) => { try { navigator.mediaSession.setActionHandler(action, handler); } catch (_) {} });
  load(0);
})();
